#! /bin/sh


### BEGIN INIT INFO
# Provides:         bluetooth and wifi
# Required-Start:   
# Required-Stop:    
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
### END INIT INFO

sudo hciconfig hci0 up
sudo ifup wlan0
cd /home/pi/github/tikicam-config/
sudo git pull
python update_github.py
cd /home/pi
sudo python /home/pi/github/picamera-auto/picam.py &
sudo python /home/pi/github/bluetooth-proximity-tracker/le_scanner.py &
